[build]
  # Comando para construir el proyecto Angular
  command = "npm run build"
  # Directorio que contiene los archivos construidos para publicar
  publish = "dist/mi-app/browser"

[build.environment]
  # Versión de Node.js a utilizar
  NODE_VERSION = "20"

# Configuración para manejar las rutas de Angular (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad adicionales
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuración de caché para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

